### ISSUE TITLE
Finish standardisation of docstrings 

### ISSUE THREAD

**Issue by DavidMcCann-NOC** [NOC-EO/seastar_project#171]
Need to run Sphinx and/or liaise with Clive to settle on the working docstring format and standardise the language / descriptions used.

Any changes to be retroactively applied to current function docstrings

**Comment by ACHMartin** [comment]
This need to be done earlier rather than later otherwise we will lose some time to do it again. The documentation might be useful for us as well (for me definitely as I am not very familiar with all functions).

**Comment by DavidMcCann-NOC** [comment]
Sphinx is now running on my test branch. Still need to fill out docstrings for the remaining functions and tidy them up retroactively before settling on the new (numpy) docstring standard
