### ISSUE TITLE
Get pre-processing fields like incidence angle, squint, ... (computed with MetaSensing script or intern script)

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#175]
Either 1/ we use Matlab to compute the fields and add it to the netcdf, or 2/ we translate the code to python

If 1/ is easy, we can do a pre-processing with this.

**Comment by DavidMcCann-NOC** [comment]
Closed with #187 - pre-computed fields to be stored alongside OSCAR data

**Comment by DavidMcCann-NOC** [comment]
This is now to be dealt with in a matlab batch script that computes these auxiliary fields and then adds them to the netcdf files permanently, rather than storing them alongside
