### ISSUE TITLE
Change AntennaAzimuthImage with computed Squint fields

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#177]
In Oscar/level1

Change the fixed squint reference 45, 135, with the one computed either via python or via MetaSensing pre-processing cf #175.
A sensible name for this field might be SquintImage.

 if antenna == 'fore':
        ds['AntennaAzimuthImage'] = np.mod(ds.OrbitHeadingImage - 45, 360)
    elif antenna == 'aft':
        ds['AntennaAzimuthImage'] = np.mod(ds.OrbitHeadingImage - 135, 360)

**Comment by ACHMartin** [comment]
use the ds.SquintAngleImage

**Comment by DavidMcCann-NOC** [comment]
Closed with #187
