### ISSUE TITLE
move init_auxiliary and generate_wind_field to a new folder?

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#179]
Should we move this in an other directory?
Which one, retrieval/level2, an other one?

In init_auxiliary, 'dsa' and 'def' can be deleted as input.
Change u10 and wind_direction to be NON-positional variable. (I don't know how to do it without given a default value. We might give a default value, u10=7, wdir=0 or 90 for North or East).

Perhaps generate_wind_field... is sufficient, no need for init_auxiliary

**Comment by ACHMartin** [comment]
in generate_wind_field... we need to remove the specific "CrossRange", "GroundRange"

**Comment by DavidMcCann-NOC** [comment]
Perhaps a new module called 'auxilliary' for any functions pertaining to this? We can decide next time we have a chat and move them.

I'm not sure what you mean by non-positional value I'm afraid! Currently this function generates a simple find field from single wind data inputs, however in the future we are likely to be using better data than this, it may well become obsolete?

**Comment by DavidMcCann-NOC** [comment]
Closed with #244
