### ISSUE TITLE
What outputs for each function: Full DataSet with the additional fields or the computed DataArray

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#182]
We tend to do return the full DataSet with the additional field.
Should we return the DataArray instead. I think it believe of the cases, perhaps we can discuss here the cases where DataArray output should be prefer.
The new API would be:
`dsl2['newField'] = compute_new_field(dsl2)`
instead of the current:
`dsl2 = compute_new_field(dsl2)`

**Comment by DavidMcCann-NOC** [comment]
I've had similar thoughts, and it wouldn't be too much effort to change. It'll be more transparent in a lot of cases I think

**Comment by DavidMcCann-NOC** [comment]
Closed with #224
