### ISSUE TITLE
For L2 datafields add longitude, latitude and time as coordinates (using these exact names for automatic detection from Xarray)

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#185]
- use the exact names (longitude or Lon, latitude or lat and time) for automatic detection from Xarray
- lon, lat and time should only have dimension in GroundRange, CrossRange, not in the Antenna direction (this should be constant whatever the antenna)

**Comment by DavidMcCann-NOC** [comment]
longitude and latitude added as coordinates to the L2 dataset in init_level2:

level2 = xr.Dataset()
level2.coords['longitude'] = level1.sel(Antenna='Fore').LonImage
level2.coords['latitude'] = level1.sel(Antenna='Fore').LatImage
level2 = level2.drop('Antenna')

The data comes from the L1 dataset which is currently merged as 'inner'. If I can think of a better way to get the lat/lon coordinate data another way then i'll adapt this, likely with issue #181

**Comment by DavidMcCann-NOC** [comment]
Closed with pull request #192
