### ISSUE TITLE
LookDirection or AntennaAzimuthImage

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#204]
In Doppler (perhaps other section) is LookDirection or AntennaAzimuthImage we should be used?

**Comment by ACHMartin** [comment]
Using "LookDirection" in "test_seastar_doppler_package_adrien_v0.ipynb" it raises an error.
We need to correct all files + documentation where "LookDirection" is mentioned, including modification of the notebook. It is a standalone notebook without the local path, so I think we could remove the "adrien".

**Comment by DavidMcCann-NOC** [comment]
I agree its confusing semantics. LookDirection as the variable Metasensing have provided denotes the port/starboard pointing direction of the arrays and is a single letter L or R (always L in our case). So I agree, perhaps we need to find a different phrase for the documentation in other functions. Perhaps 'Antenna direction' or 'Antenna location'?

The only place we actually use it in Doppler is the exception:
if len(L1.LookDirection.shape) > 2:
        raise Exception('L1.LookDirection need to be a 2D field. \n'
                        'Use e.g. L1.sel(Antenna="Fore") to reduce to '
                        'a 2D field.')
Which looks to me to be expecting IncidenceAngleImage?

**Comment by ACHMartin** [comment]
Thank you for the explanation. Indeed, either IncidenceAngleImage or AntennaAzimuthImage.

**Comment by ACHMartin** [comment]
link to #211

**Comment by DavidMcCann-NOC** [comment]
Closed with #211
