### ISSUE TITLE
Implement compute_nrcs: a wrap up for nrcs/nscat4ds

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#205]
To implement a wrap up function around nscat4ds called compute_nrcs(L1, aux_geo, gmf) following the same structure as "doppler/compute_wasv". "compute_nrcs" should accept whatever dimension including Antenna (which is not the case in compute_wasv).
In compute_wasv we align the fields within the function, perhaps we can decide just to check the function are aligned/same dimension and due the alignement outside this function.

**Comment by DavidMcCann-NOC** [comment]
Believed to be closed with commit #207
