### ISSUE TITLE
Update on the squint definition

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#225]
Cf Karlus Macedo email the 11/01/2023 "Re: OSCAR ground range; 17 Aft phase; 22nd star pattern".

Karlus give an update of the Matlab scripts to calculate Squint angle (slant squint and ground squint).

What we call "Squint" is the "Ground Squint", I propose to keep the name of the variable as "Squint" but we might update the long name/description with the "Ground Squint".
We might want to add a variable "SquintMounted" which correspond to the "slant squint".

**Comment by DavidMcCann-NOC** [comment]
Closed with #242
