### ISSUE TITLE
Remove compute_incidence_angle_from_simple_geometry

### ISSUE THREAD

**Issue by DavidMcCann-NOC** [NOC-EO/seastar_project#229]
This function is now obsolete and can be removed, to be replaced instead with an exception if ``IncidenceAngleImage`` is not present in the dataset

**Comment by ACHMartin** [comment]
what about "compute_incidence_angle_from_GBPGridInfo"

**Comment by DavidMcCann-NOC** [comment]
> what about "compute_incidence_angle_from_GBPGridInfo"

Yeah that can go as well as its now all done as pre-processing with the matlab scripts

**Comment by DavidMcCann-NOC** [comment]
Closed with #231
