### ISSUE TITLE
Need to move "generate_wind_field_from_single_measurement"

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#239]
"generate_wind_field_from_single_measurement()" is currently in retrieval/level2.py, I don't think it makes much sense to have it here. I propose to move to "scene_generation.py".

scene_generation.py should be moved to a different package than "performance", but I don't know where...

To Be Discussed

**Comment by DavidMcCann-NOC** [comment]
I agree - I always felt it was the wrong place for it to live.

Issue #179 asks about this too. I don't particularly like the idea of an 'auxiliary' package, as auxiliary can mean different things in context. I suppose we're dealing with geophysical / environmental data - something like that?

**Comment by DavidMcCann-NOC** [comment]
Closed with #244
