### ISSUE TITLE
move and adapt level1/generate_wind_field_from_single_measurement(u10, wind_direction, ds):

### ISSUE THREAD

**Issue by ACHMartin** [NOC-EO/seastar_project#243]
The function level1/generate_wind_field_from_single_measurement should move out from level1.
Potential suitable package to get this function, could be 1-performance/scene_generation or 2-utils/tools.

I tend to prefer option 1.

The function is hardly code with reference to "CrossRange" and "GroundRange", it needs to be modified.

**Comment by DavidMcCann-NOC** [comment]
Closed with #244
